//
//  UITouch+JotStylus.h
//  JotTouchSDK
//
//  Created by Timothy Ritchey on 3/3/14.
//  Copyright (c) 2014 Adonit. All rights reserved.
//

#import <UIKit/UIKit.h>

/** 
 * Identifies the source of a touch
 */
typedef NS_ENUM(NSUInteger, JotTouchIdentificationType) {
    /** There is not yet enough information to classify the source of this touch */
    JotTouchIdentificationTypeUnknown,
    /** The touch is generated by a stylus */
    JotTouchIdentificationTypeStylus,
    /** The touch is definitively not generated by a stylus (most likely a palm or finger) */
    JotTouchIdentificationTypeNotStylus
};

/**
 * Provides additional information about the source of each UITouch
 */
@interface UITouch (JotStylus)

/**
 * Identifies whether or not the SDK thinks this UITouch is being generated by a Jot
 */
@property (assign, nonatomic) JotTouchIdentificationType jotTouchIdentification;

@end
