//
//  adonitTouchTypeIdentifier.h
//  AdonitSDK
//
//  Created by Timothy Ritchey on 4/29/15.
//  Copyright (c) 2015 Adonit. All rights reserved.
//

#import "UITouch+AdonitIdentification.h"

@interface AdonitTouchTypeIdentifier : NSObject

/**
 * We will classify events with a type of UITouch to determine if they belong to an Adonit device. Ideally you would send us the event for processing before your applications main sendEvent so that we can identify Adonit devices prior to your views & gestures receiving touches generated by them.
 */
- (void)classifyAdonitDeviceIdentificationForEvent:(UIEvent *)event;

@end
