//
//  UITouch+JotStylus.h
//  AdonitSDK
//
//  Created by Timothy Ritchey on 3/3/14.
//  Copyright (c) 2014 Adonit. All rights reserved.
//

#import <UIKit/UIKit.h>

/** 
 * Identifies the source of a touch
 */
typedef NS_ENUM(NSUInteger, AdonitTouchIdentificationType) {
    AdonitTouchIdentificationTypeUnknown,
    AdonitTouchIdentificationTypeNotDevice,
    AdonitTouchIdentificationTypePotentialDevice,
    AdonitTouchIdentificationTypeStylus,
    AdonitTouchIdentificationTypeDebugPlaceholder
};

/**
 * Provides additional information about the source of each UITouch
 */
@interface UITouch (AdonitIdentification)

/**
 * Identifies whether or not the SDK thinks this UITouch is being generated by an Adonit Device
 */
@property (assign, nonatomic) AdonitTouchIdentificationType adonitTouchIdentification;

@end
